# Generated by Django 4.1.5 on 2023-01-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='ddffss', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
